paramters:
- siteCodeCount:
    type : number

stages:
- ${{ if eq(${{ parameters.siteCodeCount }}, 3)}}:
  - stage: bonus_stage
    condition : always()
    displayName: Echo a bonus stage value!
    jobs:
    - job:
      steps :
      - task : Bash@3
        inputs :
          targetType : "inline"
          script : |
            echo "BONUS STAGE"
