stages:
- stage: first
  jobs:
  - job: run
    steps:
    - checkout : none
    - task : Bash@3
      inputs : 
        targetType : "inline"
        script : |
          echo $(one)

    - task : Bash@3
      name : fatbutt
      inputs : 
        targetType : "inline"
        script : |
          echo "Editing the value"
          echo '##vso[task.setvariable variable=myOutputVar;isOutput=true]newValue'

    - task : Bash@3
      inputs : 
        targetType : "inline"
        script : |
          echo $(one) #outputs secondValue
          echo $(fatbutt.myOutputVar)

  - job: check
    dependsOn : run
    variables : 
      #myTest : "this is my test"
      myTest : $[ dependencies.run.outputs['fatbutt.myOutputVar'] ]
    steps:
    - checkout : none
    - task : Bash@3
      inputs : 
        targetType : "inline"
        script : |
          echo $(one) # outputs initialValue
          
          # Try and get this to be newValue
          echo $(myTest)
