pool:
  name : VMSS

stages:
- stage: A
  jobs:
  - job: A1
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo 'Hello world'
