pool:
  name: kata

variables:
- name: holder
  value: "Initial Value"

stages:
- template: sitecode.yml
- stage: echostage
  dependsOn:
  - setupstage
  variables:
    holder: "$[stageDependencies.setupstage.setup.outputs['echoupdate.holder']]"

  jobs:
  - job: 
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script:  |
          echo "Updated: $(holder)"
