pool:
  name : linux

parameters:
- name: 'siteCodes'
  type: object
  default: ['sa01', 'zz04', 'zz09']

stages:
- ${{ each siteCode in parameters.siteCodes }}:
  - template : stages.yml
    parameters : 
      siteCode : ${{ siteCode }}

- ${{ if eq(length(parameters.siteCodes), 3) }}:
  - stage: bonus_stage
    condition : always()
    displayName: Echo a bonus stage value!
    jobs:
    - job:
      steps :
      - task : Bash@3
        inputs :
          targetType : "inline"
          script : |
            echo "BONUS STAGE"
