pool:
  name: linux

variables:
- name: holder
  value: "Initial Value"

stages:
- stage:
  jobs:
  - job: setup
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script:  |
          echo "${{ variables.holder }}"

    - task: Bash@3
      inputs:
        targetType: "inline"
        script:  |
          echo "##vso[task.setvariable variable=holder]Updated Value"

    - task: Bash@3
      inputs:
        targetType: "inline"
        script:  |
          echo "Initial : ${{ variables.holder }}"
          echo "Updated : $(holder)"
