pool:
  name : linux

parameters:
  - name: Deployments         
    type: object
    default:
      - "a"
      - "b"

steps:
  - ${{ each p in parameters.Deployments }}
    - script: 'echo ${{ p }}'