pool:
  name : linux

variables:
- name: one
  value : 1
- name: two
  value : 2
- name: three
  value : 3
- name: four
  value : 4
- name: five
  value : 5
- name: six
  value : 6
- name: seven
  value : 7
- name: eight
  value : 8

- name : stageValues
  value :
  - 1
  - 2

stages:
- ${{ each value in variables.stageValues }}
  - stage: first
    dependsOn : []
    jobs:
    - job : joba
      steps :
      - task : Bash@3
        inputs :
          targetType : "inline"
          script : |
            echo ${{ variables.one }}
      - task : Bash@3
        inputs :
          targetType : "inline"
          script : |
            echo ${{ variables.two }}

    - job : jobb
      dependsOn : joba
      steps :
      - task : Bash@3
        inputs :
          targetType : "inline"
          script : |
            echo ${{ variables.three }}

      - task : Bash@3
        inputs :
          targetType : "inline"
          script : |
            echo ${{ variables.four }}
