pool:
  name: linux

parameters:
- name: siteCode
  type: string
  default: "ZZ04"

stages:
- stage:
  jobs:
  - job:
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "${{ parameters.siteCode }}"
