pool:
  name : linux

parameters:
- name: 'siteCodes'
  type: object
  default: ['sa01', 'zz04', 'zz09']

stages:
- ${{ each siteCode in parameters.siteCodes }}:
  - stage: Sandbox_${{siteCode}}
    displayName: Echo a the site code ${{ siteCode }}
    condition : not(eq('${{siteCode}}','zz04'))
    jobs:
    - job:
      steps :
      - task : Bash@3
        inputs :
          targetType : "inline"
          script : |
            echo "Sitecode : ${{ siteCode }}"

- ${{ if eq(length(parameters.siteCodes), 3) }}:
  - stage: Sandbox_${{siteCode}}
    displayName: Echo a the site code ${{ siteCode }}
    condition : not(eq('${{siteCode}}','zz04'))
    jobs:
    - job:
      steps :
      - task : Bash@3
        inputs :
          targetType : "inline"
          script : |
            echo "Sitecode : ${{ siteCode }}"
