pool:
    name: linux

stages:
- stage:
  jobs:
  - job: 
    steps:
    - checkout: none
    - task: bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "Hello world!"
