pool:
  name: linux

stages:
- stage: first
  jobs:
  - job: firstjob
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script : |
          echo "stage first - job first - task 1"
    - task: Bash@3
      inputs:
        targetType: "inline"
        script : |
          echo "stage first - job first - task 2"

  - job: secondjob
    dependsOn: firstjob
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script : |
          echo "stage first - job second - task 1"
    - task: Bash@3
      inputs:
        targetType: "inline"
        script : |
          echo "stage first - job second - task 2"

- stage: second
  dependsOn: []
  jobs:
  - job: firstjob
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script : |
          echo "stage second - job first - task 1"
    - task: Bash@3
      inputs:
        targetType: "inline"
        script : |
          echo "stage second - job first - task 2"

  - job: secondjob
    dependsOn: firstjob
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script : |
          echo "stage second - job second - task 1"
    - task: Bash@3
      inputs:
        targetType: "inline"
        script : |
          echo "stage second - job second - task 2"

- stage: third
  dependsOn:
  - first
  - second
  jobs:
  - job : check
    steps:
    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "Finished Checking Everything"
