pool: 
  linux

stages:
- stage: first
  jobs:
  - job: firstjob
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script : |
          echo "stage 1 - job 1 - task 1"

    - task: Bash@3
      inputs:
        targetType: "inline"
        script : |
          echo "stage 1 - job 1 - task 2"

  - job: secondjob
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script : |
          echo "stage 1 - job 2 - task 1"

    - task: Bash@3
      inputs:
        targetType: "inline"
        script : |
          echo "stage 1 - job 2 - task 2"

- stage: second
  jobs:
  - job: firstjob
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script : |
          echo "stage 2 - job 1 - task 1"

    - task: Bash@3
      inputs:
        targetType: "inline"
        script : |
          echo "stage 2 - job 1 - task 2"

  - job: secondjob
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script : |
          echo "stage 2 - job 2 - task 1"

    - task: Bash@3
      inputs:
        targetType: "inline"
        script : |
          echo "stage 2 - job 2 - task 2"
