pool:
  name: linux

   
variables:
- name: holder
  value : "Initial Value"

stages:
- stage:
  jobs:
  - job: echo
    steps:
    - checkout: none
    - task: Bash@3
      displayName: "Initial"
      inputs:
        targetType: "inline"
        script: |
          echo "Compile time : ${{ variables.holder }}"

    - task: Bash@3
      displayName: "Setting"
      inputs:
        targetType: "inline"
        script: |
          echo "##vso[task.setvariable variable=holder; isOutput=true]Updated Value"

    - task: Bash@3
      displayName: "Echo"
      inputs:
        targetType: "inline"
        script: |
          echo "Compile time : ${{ variables.holder }}"
          echo "Run time : $( holder )"
