pool:
  name: linux

parameters:
- name: siteCodes
  type: object 
  default: 
  - zz01
  - zz04
  - je03

stages:
- ${{ each siteCode in parameters.siteCodes }}:
  - template: stages.yml 
    parameters:
      siteCode : "${{siteCode}}"

- ${{ if eq(length(parameters.siteCodes), 3) }}: 
  - template : bonus.yml
