pool:
  name : linux

variables:
- name : stageValues
  value : 
  - name : "first"
  - name : "second"

stages:
- stage: first
  dependsOn : []
  jobs:
  - job : joba
    steps :
    - ${{ each name in variables.stageValue }}
      - task : Bash@3
        inputs :
          targetType : "inline"
          script : |
            echo ${{ name }}