pool:
  name : VMSS

stages:
- stage: C
  dependsOn : []
  jobs:
  - job: C1
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo "Stage C, job A1, task 1"

- stage: A
  dependsOn : []
  jobs:
  - job: A1
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo "Stage A, job A1, task 1"

- stage: A2
  dependsOn : [ A ] #Stages implicitly depend on the previous task, this undoes this
  jobs:
  - job: B1
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo "Stage B, job B1, task 1"

- stage: B
  dependsOn : [] #Stages implicitly depend on the previous task, this undoes this
  jobs:
  - job: B1
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo "Stage B, job B1, task 1"

- stage: B2
  dependsOn : [ B ] #Stages implicitly depend on the previous task, this undoes this
  jobs:
  - job: B1
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo "Stage B, job B1, task 1"

