pool:
  name : linux

variables:
- name: one
  value: initialValue 

stages:
- stage: first
  jobs:
  - job: run
    steps:
    - task : Bash@3
      inputs : 
        targetType : "inline"
        script : |
          echo ${{ variables.one }} # outputs initialValue
          echo $(one)

    - task : Bash@3
      inputs : 
        targetType : "inline"
        script : |
          echo "Editing the value"
          echo '##vso[task.setvariable variable=one]secondValue'

    - task : Bash@3
      inputs : 
        targetType : "inline"
        script : |
          echo ${{ variables.one }} 
          echo $(one)

  - job: check
    steps:
    - task : Bash@3
      inputs : 
        targetType : "inline"
        script : |
          echo ${{ variables.one }} # outputs initialValue
          echo $(one)

- stage: second
  jobs:
  - job: check
    steps:
    - task : Bash@3
      inputs : 
        targetType : "inline"
        script : |
          echo ${{ variables.one }} # outputs initialValue
          echo $(one)
