pool:
  name: linux

   
variables:
- name: holder
  value : "Initial Value"

stages:
- template: sitecode.yml
- stage: last
  variables:
    bob : $[ stageDependencies.first.echo.outputs['settingup.holder']]
  jobs:
  - job: echo
    steps:
    - checkout: none
    - task: Bash@3
      inputs: 
        targetType: "inline"
        script: |
          echo "Runtime : $(bob)"
