pool:
  name : linux

variables:
  sitecodes: 
  - sa01
  - zz04
  - zz09


stages:
- ${{ each siteCode in parameters.siteCodes }}:
  - stage: Sandbox_${{siteCode}}
    displayName: Echo a the site code ${{ siteCode }}
    jobs:
    - job:
      steps :
      - task : Bash@3
        inputs :
          targetType : "inline"
          script : |
            echo "Sitecode : ${{ siteCode }}"
