pool:
  name: linux

variables:
- name: holder
  value: Initial Value

stages:
- template: extra.yml
- stage: second
  dependsOn: first
  variables:
    fromFirst : $[ stageDependencies.first.run.outputs['fatbutt.myOutputVar'] ]
  jobs: 
  - job:
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "${{ variables.holder }}"
          echo "$(fromFirst)"
