pool:
  name: linux

variables:
- name: holder
  value: Initial Value

stages:
- stage:
  jobs: 
  - job:
    steps:
    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "Hello world"
