pool:
  name: linux

variables:
- name: holder
  value: "Default Value"

stages:
- stage: setup
  jobs:
  - job: jobone
    steps:
    - checkout: none
    - task: Bash@3
      inputs: 
        targetType: "inline"
        script: |
          echo "Holder Compiled: ${{ variables.holder }}"

    - task: Bash@3
      inputs: 
        targetType: "inline"
        script: |
          echo "##vso[task.setvariable variable=holder]Updated"

    - task: Bash@3
      inputs: 
        targetType: "inline"
        script: |
          echo "Holder Compiled: ${{ variables.holder }}"
          echo "Holder Runtime: $(holder)"
