pool:
  name : linux

parameters:
- name: 'siteCodes'
  type: object
  default: ['sa01', 'zz04', 'zz09']

stages:
- stage: Sandbox
  displayName: Sandbox SQL database deployments
  jobs:
  - ${{ each siteCode in parameters.siteCodes }}:
    - job:
      steps :
      - task : Bash@3
        inputs :
          targetType : "inline"
          script : |
            echo "Hello World"
