pool:
  name: linux

variables:
- name: holder
  value: "Default Value"

stages:
- template: sitecode.yml
- stage: check
  variables:
    holder: "$[ stageDependencies.setup.jobone.outputs['setup.holder']]"
  jobs:
  - job: echocheck
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "Holder : $(holder)"
