pool:
    name: linux

stages:
- stage: 
  jobs:
  - job: 
    steps:
    - task: bash@3
      inputs:
        targetType: "inline"
        script: |
          # Download the Microsoft repository GPG keys
          wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb

          # Register the Microsoft repository GPG keys
          sudo dpkg -i packages-microsoft-prod.deb

          # Update the list of products
          sudo apt-get update

          # Install PowerShell
          sudo apt-get install -y powershell

          # Start PowerShell
          pwsh

    - task: AzureCLI@2
      inputs:
        scriptType: 'pscore'
        scriptLocation: 'scriptPath'
        scriptPath: 'arm/deploy.ps1'
        addSpnToEnvironment: true
        useGlobalConfig: true