pool:
  name: linux

parameters:
- name: siteCodes
  type: object 
  default: 
  - zz01
  - zz04
  - je03

stages:
- ${{ each siteCode in parameters.siteCodes }}
  - stage: Sandbox_${{ siteCode }
    jobs: 
    - job: echo
      steps:
      - checkout: none
      - task: Bash@3
        inputs: 
          targetType: "inline"
          script: |
            echo "Site Code : je03"
