pool:
    name: linux

stages:
- stage: stageone
  jobs:
  - job: first
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "stage 1 - job 1 - task 1"

    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "stage 1 - job 1 - task 2"

  - job: second
    dependsOn: first
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "stage 1 - job 2 - task 1"

    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "stage 1 - job 2 - task 2"

- stage: stagetwo
  dependsOn: []
  jobs:
  - job: twofirst
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "stage 2 - job 1 - task 1"

    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "stage 2 - job 1 - task 2"

  - job: second
    dependsOn: twofirst
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "stage 2 - job 2 - task 1"

    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "stage 2 - job 2 - task 2"

- stage: stagethree
  dependsOn: [ stageone, stagetwo ]
  jobs:
  - job: jobone
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script : | 
          echo "All completed!"

