pool:
  name: linux

parameters:
- name: "siteCode"
  type: string
  default: "zz01"

stages:
- stage: first
  jobs:
  - job: firstjob
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script : |
          echo "${{ parameters.siteCode}}"
