pool:
  name: linux

variables:
- name: holder
  value: "Initial Value"

stages:
- stage: setup
  jobs:
  - job: echosetup
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script : | 
            echo "Initial Value : ${{ variables.holder }}"

    - task: Bash@3
      inputs:
        targetType: "inline"
        script : | 
          echo "##vso[task.setvariable variable="holder"]Updated Value"

    - task: Bash@3
      inputs:
        targetType: "inline"
        script : | 
          echo "Initial Value : ${{ variables.holder }}"
          echo "Updated : $(holder)"
          echo "Updated : $(holder)"
