pool:
  name : linux

stages:
- stage: first
  jobs:
    - job: joba
      steps:
      - task : Bash@3
        inputs : 
          targetType : "inline"
          script : |
            echo "Hello world!"
