pool:
    name: linux

stages:
- stage: 
  jobs:
  - job: 
    steps:
    - task: bash@3
      inputs:
        targetType: "inline"
        script: |
            echo "Hello World"

    - task: AzureCLI@2
      inputs:
        scriptType: 'pscore'
        scriptLocation: 'scriptPath'
        scriptPath: 'arm/deploy.ps1'
        addSpnToEnvironment: true
        useGlobalConfig: true