pool:
  name: linux

parameters:
- name: siteCode
  type: string
  default: zz01

- name: siteCodes
  type: object
  default:
  - ZZ01
  - ZZ04
  - JE03

stages:
- stage: sitecode_${{parameters.siteCode}}
  jobs:
  - job: ${{ parameters.siteCode }}
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "${{ parameters.siteCode }}"

- ${{ each siteCode in parameters.siteCodes }}:
  - stage: ${{ siteCode }}
    jobs:
    - job: ${{ siteCode }}
      steps:
      - checkout: none
      - task: Bash@3 
        inputs: 
          targetType: "inline"
          script: | 
            echo "${{ siteCode }}"
