parameters:
- name: siteCode
  type: string
  default: JEFF

- name: siteCodes
  type: object
  default:
  - ZZ01
  - ZZ04
  - JE03

pool:
    name: linux

stages:
- stage: one
  jobs:
  - job: jobeone
    steps:
    - checkout: none
    - task: bash@3
      inputs:
        targetType: "inline"
        script: |
            echo "SiteCode : ${{ parameters.siteCode }}"

- ${{ each siteCode in parameters.siteCodes }}:
  - stage: ${{ siteCode }}
    condition: not(eq('ZZ04', '${{ siteCode }}'))
    dependsOn: []
    jobs:
    - job: 
      steps:
      - checkout: none
      - task: bash@3
        inputs:
          targetType: "inline"
          script:
            echo "SiteCode ${{ siteCode }}"

- ${{ if length(parameters.siteCodes) }}:
  - stage: bonus
    dependsOn:
    - one
    - ${{ each siteCode in parameters.siteCodes }}:
      - ${{ siteCode }}
    jobs:
    - job: first
      steps:
      - checkout: none
      - task: bash@3
        inputs:
          targetType: "inline"
          script: |
            echo BONUS
