pool: 
    linux

stages:
- stage: first
      jobs:
      - job: firstjob
        steps:
        - task: Bash@3
          inputs:
              targetType: "inline"
              script : |
                  echo "Fat PEEN"

