pool:
  name: linux

variables:
- name: holder
  value: Initial Value

stages:
- stage:
  jobs: 
  - job: joba
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "${{ variables.holder }}"

    - task: Bash@3
      name : fatbutt
      inputs:
        targetType: "inline"
        script: |
          echo "##vso[task.setvariable variable=holder;isOutput=true]Updated Value"

    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "${{ variables.holder }}"
          echo $(fatbutt.holder)

  - job: jobb
    dependsOn: joba
    variables:
        myTest: $[ dependencies.joba.outputs['fatbutt.holder'] ]
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "${{ variables.holder }}"
          echo $( myTest )

- stage:
  jobs: 
  - job:
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "${{ variables.holder }}"
          echo "$( holder )"
