pool:
  name: linux

parameters:
- name: siteCode
  type: string
  default: zz01

- name: siteCodes
  type: object
  default:
  - ZZ01
  - ZZ04
  - JE03

stages:
- stage: sitecode_${{parameters.siteCode}}
  jobs:
  - job: ${{ parameters.siteCode }}
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "${{ parameters.siteCode }}"
    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "${{ join(',',parameters.siteCodes.*.value) }}"

- ${{ each siteCode in parameters.siteCodes }}:
  - template: sitecode.yml
    parameters:
      siteCode: ${{ siteCode }}

- ${{ if eq(length(parameters.siteCodes), 3) }}:
  - stage: bonus
    condition: always()
    dependsOn: 
    - sitecode_${{ parameters.siteCode }}
    - ${{ each siteCode in parameters.siteCodes }}:
      - ${{ siteCode }}

    jobs:
    - job: echo
      steps:
      - checkout: none
      - task: Bash@3
        inputs:
          targetType: "inline"
          script: |
            echo "Bonus Get"


