pool:
  name: linux

   
variables:
- name: holder
  value : "Initial Value"

stages:
- stage: first
  jobs:
  - job: echo
    steps:
    - checkout: none
    - task: Bash@3
      displayName: "Initial"
      inputs:
        targetType: "inline"
        script: |
          echo "Compile time : ${{ variables.holder }}"

    - task: Bash@3
      name: settingup
      inputs:
        targetType: "inline"
        script: |
          echo "##vso[task.setvariable variable=holder;isOutput=true]Updated Value"

    - task: Bash@3
      displayName: "Echo"
      inputs:
        targetType: "inline"
        script: |
          echo "Compile time : ${{ variables.holder }}"
          echo "Runtime : $(settingup.holder)"

  - job: updated
    dependsOn : echo
    variables:
      bob : $[ dependencies.echo.outputs['settingup.holder']]
    steps:
      - checkout: none
      - task: Bash@3
        inputs:
          targetType: "inline"
          script: |
            echo "Run time : $(bob)"

- stage: last
  variables:
    bob : $[ stageDependencies.first.echo.outputs['settingup.holder']]
  jobs:
  - job: echo
    steps:
    - checkout: none
    - task: Bash@3
      inputs: "inline"
      script: |
        echo "Runtime : $(bob)"
