parameters:
- name: siteCode
  type: string
  default: JEFF

pool:
    name: linux

stages:
- stage: one
  jobs:
  - job: jobeone
    steps:
    - checkout: none
    - task: bash@3
      inputs:
        targetType: "inline"
        script: |
            echo "SiteCode : ${{ parameters.siteCode }}"
