pool:
  name: linux

stages:
- stage: first
  jobs:
  - job: job_one
    steps:
    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "stage 1 - job 1 - task 1"

    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "stage 1 - job 1 - task 2"

  - job: job_two
    steps:
    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "stage 1 - job 2 - task 1"

    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "stage 1 - job 2 - task 2"

- stage: second
  jobs:
  - job: job_one
    steps:
    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "stage 2 - job 1 - task 1"

    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "stage 2 - job 1 - task 2"

  - job: job_two
    steps:
    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "stage 2 - job 2 - task 1"

    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "stage 2 - job 2 - task 2"
