pool:
  name : Azure Pipelines

stages:
- stage: C
  dependsOn : []
  jobs:
  - job: C1
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo "Stage C, job A1, task 1"
