pool:
  name: linux

parameters:
- name: siteCode
  type: string
  default: zz01

stages:
- stage: sitecode_${{parameters.siteCode}}
  jobs:
  - job: ${{ parameters.siteCode }}
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "${{ parameters.siteCode }}"
