pool:
  name : linux

stages:
- stage: first
  jobs:
  - job: echo_one
    steps:
    - checkout : none
    - task : Bash@3
      inputs : 
        targetType : "inline"
        script : |
            echo "first - echo_one - 1"

    - task : Bash@3
      inputs : 
        targetType : "inline"
        script : |
            echo "first - echo_one - 2"

  - job: echo_two
    dependsOn : echo_one
    steps:
    - checkout : none
    - task : Bash@3
      inputs : 
        targetType : "inline"
        script : |
            echo "first - echo_two - 1"

    - task : Bash@3
      inputs : 
        targetType : "inline"
        script : |
            echo "first - echo_two - 2"

- stage: second
  dependsOn : []
  jobs:
  - job: echo_one
    steps:
    - checkout : none
    - task : Bash@3
      inputs : 
        targetType : "inline"
        script : |
            echo "second - echo_one - 1"

    - task : Bash@3
      inputs : 
        targetType : "inline"
        script : |
            echo "second - echo_one - 2"

  - job: echo_two
    dependsOn : echo_one
    steps:
    - checkout : none
    - task : Bash@3
      inputs : 
        targetType : "inline"
        script : |
            echo "second - echo_two - 1"

    - task : Bash@3
      inputs : 
        targetType : "inline"
        script : |
            echo "second - echo_two - 2"

- stage : third
  dependsOn : 
    - first
    - second
  jobs:
    - job : final
      steps:
      - task : Bash@3
        inputs : 
          targetType : "inline"
          script : |
            echo "final"
