pool:
  name: linux

parameters:
- name: siteCode
  default: "zz04"
  type: string

stages:
- stage:
  jobs:
  - job: first
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "Hello World!"
