pool:
  name: linux

parameters:
- name: siteCode
  default: "zz04"
  type: string
- name: siteCodes
  type: object
  default:
  - zz01
  - zz04
  - je03

stages:
- stage:
  jobs:
  - job: echo
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "siteCode : ${{ parameters.siteCode }}"

- ${{ each siteCode in parameters.siteCodes }}:
  - stage: ${{ siteCode }}
    jobs:
    - job: echo
      steps:
      - checkout: none
      - task: Bash@3
        inputs:
          targetType: "inline"
          script: |
            echo "siteCode : ${{ parameters.siteCode }}"

- ${{ if eq(length( parameters.siteCodes ), 3) }}:
  - stage: bonus_get
    jobs:
      - job:
        steps:
          - checkout: none
          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                echo "BONUS GET"


