pool:
  name : linux

stages:
- stage: first
  jobs:
    - job: joba
      steps:
      - task : Bash@3
        inputs : 
          targetType : "inline"
          script : |
            echo "Setting up the value";
            echo '##vso[task.setvariable variable=one]first';

      - task : Bash@3
        inputs : 
          targetType : "inline"
          script : |
            echo "Echoing the value : $one"
