pool:
  name : linux

stages:
- stage: first
  dependsOn : none
  jobs:
  - job : 
    steps :
    - task : Bash@3
      inputs :
        targetType : "inline"
        script : |
          echo "Hello World"
    - task : Bash@3
      inputs :
        targetType : "inline"
        script : |
          echo "Hello World"

  - job : 
    steps :
    - task : Bash@3
      inputs :
        targetType : "inline"
        script : |
          echo "Hello World"
    - task : Bash@3
      inputs :
        targetType : "inline"
        script : |
          echo "Hello World"
      
- stage: second
  dependsOn : none
  jobs:
  - job : 
    steps :
    - task : Bash@3
      inputs :
        targetType : "inline"
        script : |
          echo "Hello World"
    - task : Bash@3
      inputs :
        targetType : "inline"
        script : |
          echo "Hello World"

  - job : 
    steps :
    - task : Bash@3
      inputs :
        targetType : "inline"
        script : |
          echo "Hello World"
    - task : Bash@3
      inputs :
        targetType : "inline"
        script : |
          echo "Hello World"

- stage : final
  dependsOn : 
  - first
  - second
  jobs:
  - job : 
    steps :
    - task : Bash@3
      inputs:
        targetType : "inline"
        script : |
          echo "Finished!"
