pool:
  name: linux

parameters:
- name: siteCode
  type: string
  default: "ZZ04"
- name: siteCodes
  type: object
  default:
  - ZZ01
  - ZZ04
  - JE03

stages:
- stage: zz04
  jobs:
  - job:
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "SiteCode : ${{ parameters.siteCode }}"

- ${{ each siteCode in parameters.siteCodes }}:
  - stage: "each_${{ siteCode }}"
    jobs:
    - job:
      steps:
      - checkout: none
      - task: Bash@3
        inputs:
          targetType: "inline"
          script: |
            echo "SiteCode : ${{ siteCode }}"

- ${{ if eq(length( parameters.siteCodes ), 3) }}:
  - stage: bonus
    jobs:
    - job:
      steps:
      - task: Bash@3
        inputs:
          targetType: "inline"
          script: |
            echo BONUS GET
