pool:
  name : linux

variables:
- name: one
  value: initialValue 

stages:
- stage: first
  jobs:
  - job: run
    steps:
    - task : Bash@3
      inputs : 
        targetType : "inline"
        script : |
          echo ${{ variables.one }} # outputs initialValue
          echo $(one)

    - task : Bash@3
      name : fatbutt
      inputs : 
        targetType : "inline"
        script : |
          echo "Editing the value"
          echo '##vso[job.setvariable variable=one]secondValue'
          echo '##vso[job.setvariable variable=myOutputVar]newValue'

    - task : Bash@3
      inputs : 
        targetType : "inline"
        script : |
          echo ${{ variables.one }} # outputs initialValue
          echo $(one) #outputs secondValue
          echo $(fatbutt.myOutputVar)

  - job: check
    steps:
    - task : Bash@3
      inputs : 
        targetType : "inline"
        script : |
          # Try and get this to be secondValue
          echo $(one) # outputs initialValue

- stage: second
  jobs:
  - job: check
    steps:
    - task : Bash@3
      inputs : 
        targetType : "inline"
        script : |
          echo $(one)# outputs initialValue
