pool:
  name: linux

parameters:
- name: siteCode
  type: string
  default: zz01

- name: siteCodes
  type: object
  default:
  - ZZ01
  - ZZ04
  - JE03

stages:
- stage: sitecode_${{parameters.siteCode}}
  jobs:
  - job: ${{ parameters.siteCode }}
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "${{ parameters.siteCode }}"

- ${{ each siteCode in parameters.siteCodes }}:
  - stage: ${{ siteCode }}
    dependsOn: []
    jobs:
    - job: ${{ siteCode }}
      steps:
      - checkout: none
      - task: Bash@3 
        inputs: 
          targetType: "inline"
          script: | 
            echo "${{ siteCode }}"

- ${{ if eq(length(parameters.siteCodes), 3) }}:
  - stage: bonus
    //might need to add a depends on, sitecode_, and parameters.siteCodes, then join those 2 arrays
    dependsOn: ${{parameters.siteCodes}}
    jobs:
    - job: echo
      steps:
      - checkout: none
      - task: Bash@3
        inputs:
          targetType: "inline"
          script: |
            echo "Bonus Get"


