pool:
  name: linux

variables:
- name: holder
  value: "Initial Value"

stages:
- template: sitecode.yml
- stage: stagetwo
  dependsOn:
  - setup
  variables:
    holder : "$[ stageDependencies.setup.echosetup.outputs['set.holder']]"
  jobs:
  - job: anotherechocheck
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script : | 
          echo "Holder : $(holder)"
