parameters:
- name: sitecode
  type: string

stages:
- stage: 
  jobs:
  - job:
    steps:
    - checkout: none
    - task: bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "SiteCode : ${{ parameters.siteCode }}"
