parameters:
- name: siteCode
  type: string


stages:
- stage: ${{ parameters.siteCode }}
  condition: not(eq('${{ parameters.siteCode }}', 'ZZ04'))
  dependsOn: []
  jobs:
  - job: ${{ parameters.siteCode }}
    steps:
    - checkout: none
    - task: Bash@3 
      inputs: 
        targetType: "inline"
        script: | 
          echo "${{ parameters.siteCode }}"
