parameters:
- name: siteCode
  type: string

stages:
- stage: "each_${{ parameters.siteCode }}"
  condition: not(eq('${{parameters.siteCode}}', 'ZZ04'))
  jobs:
  - job:
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: "inline"
        script: |
          echo "SiteCode : ${{ parameters.siteCode }}"
